name: CI

on:
  workflow_dispatch:
    inputs:
      aceBoxVersion:
        description: 'ACE-Box version'
        default: '1.21.0'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - shell: bash
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET_NAME }}
          # TEST_SECRET: "_valid"
        run: |
          if [ "$TEST_SECRET" = "valid" ]; then
            echo "TEST_SECRET has the value 'valid'"
          else
            echo "TEST_SECRET has a different value"
          fi

          echo "ACE-Box version ${{ inputs.aceBoxVersion }} will be deployed"
